apiVersion: v1
kind: Service
metadata:
  name: mlops-assignment-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: mlops-assignment-app